version: "3.1"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 22183:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=true
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29094:29092
      - 29095:29093
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093,BROKER://0.0.0.0:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093,BROKER://localhost:29093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=true
  db_cardholder:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cardholder
    ports:
      - 5430:5432
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'