spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/cardholder?currentSchema=cardholder
    username: postgres
    password: secret
  flyway:
    user: postgres
    password: secret
    schemas: cardholder
    url: jdbc:postgresql://localhost:5430/cardholder?currentSchema=cardholder
    enabled: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true


  #  spring.jpa.hibernate.ddl-auto= update
  #  spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
  #spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

  # Hibernate ddl auto (create, create-drop, validate, update)